### ISSUE TITLE
Error while installing for Python3

### ISSUE THREAD

**Issue by ekerstein** [adrienemery/lnd-grpc-client#5]
I'm having trouble installing this with Python3. I'm on Ubuntu, Python 3.5.2, Pip 9.0.1. I get this error:

Collecting lndgrpc
  Downloading https://files.pythonhosted.org/packages/51/70/f356ec69c1d8f4da5b59bc42c2aba5ce62cda6db8c00491833c44e07461f/lndgrpc-0.1.2-py3-none-any.whl
Collecting aiogrpc (from lndgrpc)
  Could not find a version that satisfies the requirement aiogrpc (from lndgrpc) (from versions: )
No matching distribution found for aiogrpc (from lndgrpc)

**Comment by adrienemery** [comment]
@ekerstein ah looks like `aiogrpc` dependency is python 3.6 only - I'll update to not include the async rpc client for python 3.5 installs.

Thanks for the ticket. Should have a fresh release shortly.

**Comment by adrienemery** [comment]
fixed in f3b963d0cc940635afada86f8d380ae363eab646

**Comment by adrienemery** [comment]
can re-install new version which should fix it -> tested with python 3.5 this time :)

**Comment by ekerstein** [comment]
Thanks, it works!
