### ISSUE TITLE
Update channel max message length

### ISSUE THREAD

**Issue by adrienemery** [adrienemery/lnd-grpc-client#9]
Need to update max size based on https://github.com/lightningnetwork/lnd/pull/2374

Update the channel creation to include the following options 
```python
channel = self.grpc_module.secure_channel(self.ip_address, self._credentials, options=[('grpc.max_receive_message_length',1024*1024*50)])

```

**Comment by takinbo** [comment]
@adrienemery you may want to close this issue as it has been resolved.

**Comment by adrienemery** [comment]
@takinbo 👍cut a new release thanks for the PR
